root = "."
tmp_dir = "tmp"

[build]
cmd = "swag init -g ./cmd/server/main.go -d . -o docs --parseInternal --parseDependency && go build -o ./tmp/main ./cmd/server/main.go"
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air.log"

[log]
time = true

[screen]
clear_on_rebuild = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true