root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/walkit ./cmd/server/"
bin = "bin/walkit"
full_bin = "APP_ENV=development ./bin/walkit"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
include_dir = ["cmd", "config", "internal", "pkg"]
exclude_file = []
delay = 500  
stop_on_error = true
log = "air.log"
kill_delay = "0.5s"
send_interrupt = true

[log]
time = true 

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true