root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/walkit ./cmd/server/"  # Correctly pointing to the server directory
bin = "bin/walkit"
full_bin = "APP_ENV=development ./bin/walkit"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
include_dir = ["cmd", "config", "internal", "pkg"]  # Include all directories where Go files reside
exclude_file = []
delay = 1000
stop_on_error = true
log = "air.log"

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true