basePath: /api/v1
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  github_com_rowjay007_walkit_internal_model.Exercise:
    properties:
      category:
        type: string
      created:
        type: string
      description:
        type: string
      duration:
        type: integer
      id:
        type: string
      intensity:
        type: string
      muscleGroup:
        items:
          type: string
        type: array
      name:
        type: string
      updated:
        type: string
    type: object
  github_com_rowjay007_walkit_internal_model.ExerciseSet:
    properties:
      duration:
        type: integer
      exerciseId:
        type: string
      notes:
        type: string
      reps:
        type: integer
      sets:
        type: integer
      weight:
        type: number
    type: object
  github_com_rowjay007_walkit_internal_model.LoginRequest:
    properties:
      identity:
        maxLength: 100
        minLength: 3
        type: string
      password:
        maxLength: 100
        minLength: 8
        type: string
    required:
    - identity
    - password
    type: object
  github_com_rowjay007_walkit_internal_model.LoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.User'
    type: object
  github_com_rowjay007_walkit_internal_model.Response:
    properties:
      data: {}
      error:
        example: Error message
        type: string
      message:
        example: Success message
        type: string
    type: object
  github_com_rowjay007_walkit_internal_model.UpdateUserRequest:
    properties:
      activityLevel:
        type: string
      avatar:
        type: string
      email:
        type: string
      fitnessGoal:
        type: string
      username:
        type: string
    type: object
  github_com_rowjay007_walkit_internal_model.User:
    properties:
      activityLevel:
        type: string
      avatar:
        type: string
      created:
        type: string
      email:
        type: string
      emailVisibility:
        type: boolean
      fitnessGoal:
        type: string
      id:
        type: string
      password:
        type: string
      passwordConfirm:
        type: string
      updated:
        type: string
      username:
        type: string
    type: object
  github_com_rowjay007_walkit_internal_model.WorkoutPlan:
    properties:
      created:
        type: string
      description:
        type: string
      exercises:
        items:
          $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.ExerciseSet'
        type: array
      id:
        type: string
      name:
        type: string
      schedule:
        $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.WorkoutSchedule'
      updated:
        type: string
      userId:
        type: string
    type: object
  github_com_rowjay007_walkit_internal_model.WorkoutSchedule:
    properties:
      days:
        items:
          type: string
        type: array
      endDate:
        type: string
      startDate:
        type: string
      time:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A fitness workout tracking API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Walkit API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a token
      parameters:
      - description: Login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
      summary: Login user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user in the system
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Register new user
      tags:
      - auth
  /exercises:
    post:
      consumes:
      - application/json
      description: Create a new exercise with the provided details
      parameters:
      - description: Exercise details
        in: body
        name: exercise
        required: true
        schema:
          $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.Exercise'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Create new exercise
      tags:
      - exercises
  /exercises/{id}:
    get:
      consumes:
      - application/json
      description: Get details of a specific exercise
      parameters:
      - description: Exercise ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.Exercise'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get exercise by ID
      tags:
      - exercises
  /users/me:
    get:
      consumes:
      - application/json
      description: Get details of the currently authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.User'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - ApiKeyAuth: []
      summary: Get current user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update the currently authenticated user's details
      parameters:
      - description: User update details
        in: body
        name: update
        required: true
        schema:
          $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - ApiKeyAuth: []
      summary: Update current user
      tags:
      - users
  /workouts:
    post:
      consumes:
      - application/json
      description: Create a new workout plan
      parameters:
      - description: Workout details
        in: body
        name: workout
        required: true
        schema:
          $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.WorkoutPlan'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.WorkoutPlan'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.Response'
      summary: Create new workout
      tags:
      - workouts
  /workouts/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an existing workout plan
      parameters:
      - description: Workout ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.Response'
      summary: Delete workout
      tags:
      - workouts
    get:
      consumes:
      - application/json
      description: Get details of a specific workout
      parameters:
      - description: Workout ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.WorkoutPlan'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.Response'
      summary: Get workout by ID
      tags:
      - workouts
    put:
      consumes:
      - application/json
      description: Update an existing workout plan
      parameters:
      - description: Workout ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated workout details
        in: body
        name: workout
        required: true
        schema:
          $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.WorkoutPlan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rowjay007_walkit_internal_model.Response'
      summary: Update workout
      tags:
      - workouts
swagger: "2.0"
